name: Run script daily

on:
  schedule:
    - cron: '0 0 * * *'  # 00:00 UTC every day = 1am Lagos time
  workflow_dispatch:   # manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run my script
        run: node serverm.js  # change this to your command
